version: '3.8'

services:
  app:
    container_name: titanics_luck
    build: .
    shm_size: '1gb'
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
    command: python src/main.py